version: '2'
services:
    redcarpet-app:
        image: redcarpet
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://redcarpet-postgresql:5432/redcarpet
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=redcarpet-elasticsearch:9300
        ports:
            - 8080:8080
    redcarpet-postgresql:
        extends:
            file: postgresql.yml
            service: redcarpet-postgresql
    redcarpet-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: redcarpet-elasticsearch
